# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:


- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'gerardosullivan'
    scannerMode: 'other'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'spring-javaformat:apply package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sqMavenPluginVersionChoice: 'latest'
    
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
    
- task: Docker@2
  inputs:
    containerRegistry: 'Docker service connection'
    repository: 'gerardosullivan / petclinic-azure'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker service connection'
    repository: 'gerardosullivan / petclinic-azure'
    command: 'push'


