# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:


  
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'spring-javaformat:apply package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
    
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'gerardosullivan'
    scannerMode: 'MSBuild'
    projectKey: 'sonar.projecKey'
    
- task: Docker@2
  inputs:
    containerRegistry: 'Docker service connection'
    repository: 'petclinic-azure'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
